### ISSUE TITLE
Cannot find ./App.svelte

### ISSUE THREAD

**Issue by Nouw** [inertiajs/inertia-svelte#5]
I get these errors when I try to install and use the inertia-svelte packages in my symfony application.
Here is my console output of the browser:
![Console browser output](https://i-love-my-cat.s-ul.eu/HWKUAwSz)
My terminal output when compiling:
![Terminal output](https://i-love-my-cat.s-ul.eu/CdAYU4Sh)

**Comment by reinink** [comment]
What was wrong?
